//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarateManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KarateManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE IF NOT EXISTS KarateManagement;.
        /// </summary>
        internal static string CreateDB {
            get {
                return ResourceManager.GetString("CreateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Student (ID, FirstName, LastName, DateOfBirth, Address, PostalCode, PhoneNumber, Email, Hours, Belt, Balance, MembershipEndDate)
        ///VALUES (&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, &apos;{3}&apos;, &apos;{4}&apos;, &apos;{5}&apos;, &apos;{6}&apos;, &apos;{7}&apos;, &apos;{8}&apos;, &apos;{9}&apos;, &apos;{10}&apos;, &apos;{11}&apos;);.
        /// </summary>
        internal static string CreateStudent {
            get {
                return ResourceManager.GetString("CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Table Student
        ///(
        ///	ID INT PRIMARY KEY,
        ///	FirstName varchar(20),
        ///	LastName varchar(20),
        ///	DateOfBirth date,
        ///	Address varchar(100),
        ///	PostalCode char(6),
        ///	PhoneNumber varchar(10),
        ///	Email varchar(40),
        ///	Hours int,
        ///	Belt int,
        ///	Balance decimal(10,2),
        ///	MembershipEndDate date
        ///);.
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From student where ID = {0};.
        /// </summary>
        internal static string DeleteStudent {
            get {
                return ResourceManager.GetString("DeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * from Student;.
        /// </summary>
        internal static string GetAllStudents {
            get {
                return ResourceManager.GetString("GetAllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From Student where MembershipEndDate &lt; current_timestamp;.
        /// </summary>
        internal static string MembershipExpired {
            get {
                return ResourceManager.GetString("MembershipExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select MAX(ID) as ID from Student;.
        /// </summary>
        internal static string SelectMaxID {
            get {
                return ResourceManager.GetString("SelectMaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * 
        ///From student 
        ///Where id = {0};.
        /// </summary>
        internal static string SelectStudentWithID {
            get {
                return ResourceManager.GetString("SelectStudentWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;!-- File Menu--&gt;
        ///    &lt;system:String x:Key=&quot;File&quot;&gt;File&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;NewStudent&quot;&gt;New Student&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;Search&quot;&gt;Search&lt;/system:String&gt;
        ///
        ///    &lt;!-- Edit Student--&gt;
        ///    &lt;system:String x:Key=&quot;ID&quot;&gt;ID&lt;/system: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources {
            get {
                return ResourceManager.GetString("StringResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;!--File Menu--&gt;
        ///    &lt;system:String x:Key=&quot;File&quot;&gt;Fichier&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;NewStudent&quot;&gt;Nouveau Etudiant&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;Search&quot;&gt;Recherche&lt;/system:String&gt;
        ///
        ///    &lt;!--Edit Student--&gt;
        ///    &lt;system:String x:Key=&quot;ID&quot;&gt;Nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_fr_CA {
            get {
                return ResourceManager.GetString("StringResources_fr_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM Student
        ///WHERE Balance &lt;&gt; 0;.
        /// </summary>
        internal static string StudentBalance {
            get {
                return ResourceManager.GetString("StudentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM  Student
        ///WHERE  DATE_ADD(DateOfBirth, INTERVAL YEAR(CURDATE())-YEAR(DateOfBirth) YEAR) 
        ///            BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 7 DAY);.
        /// </summary>
        internal static string StudentBirthday {
            get {
                return ResourceManager.GetString("StudentBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   UPDATE `karatemanagement`.`student` 
        ///SET `FirstName` = &apos;{1}&apos;,`LastName` = &apos;{2}&apos;, `DateOfBirth` = &apos;{3}&apos;,`Address` = &apos;{4}&apos;, `PostalCode` = &apos;{5}&apos;, 
        ///	`PhoneNumber` = &apos;{6}&apos;, `Email` = &apos;{7}&apos;, `Hours` = &apos;{8}&apos;, `Belt` = &apos;{9}&apos;, `Balance` = &apos;{10}&apos;, `MembershipEndDate` = &apos;{11}&apos; 
        ///WHERE `student`.`ID` = {0};.
        /// </summary>
        internal static string UpdateStudent {
            get {
                return ResourceManager.GetString("UpdateStudent", resourceCulture);
            }
        }
    }
}
